include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "example/**"

dcm:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity:
      threshold: 20
    number-of-parameters:
      threshold: 4
    maximum-nesting-level:
      threshold: 5
  exclude:
    metrics:
      - test/**
